#!/bin/bash

_munge_setup() {
    id
    mkdir -p /run/munge
    chown munge:munge /run/munge
    sudo -u munge munged
}

_slurm_setup() {

    /usr/sbin/groupadd -r slurm 2>/dev/null    
    /usr/sbin/useradd -c "Slurm" -g slurm \
      -s /bin/false -r -d /tmp slurm 2>/dev/null

    mkdir -p /var/run/slurm
    chown slurm:slurm /var/run/slurm
    mkdir -p /var/spool/slurm
    chown slurm:slurm /var/spool/slurm

    cat > /etc/slurm/slurm.conf <<EOF

SlurmctldHost=localhost
AuthType=auth/munge
EnforcePartLimits=NO
MpiDefault=pmix
ProctrackType=proctrack/pgid
ReturnToService=0
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurm/d
SlurmUser=slurm
SlurmdUser=root
StateSaveLocation=/var/spool/slurm/ctld
SwitchType=switch/none
TaskPlugin=task/none

# TIMERS
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0

# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/linear

AccountingStorageType=accounting_storage/none
ClusterName=testcluster
JobCompType=jobcomp/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
SlurmctldDebug=3
SlurmdDebug=3
MailProg=/bin/true

# COMPUTE NODES
NodeName=$(hostname -s) CPUs=$(nproc) State=UNKNOWN
PartitionName=batch Nodes=$(hostname -s) Default=YES MaxTime=INFINITE State=UP
EOF

    sudo -u slurm slurmctld
    slurmd
}

_users_setup() {
    /usr/sbin/groupadd -r users 2>/dev/null    
    /usr/sbin/useradd -c "Demouser" -g users \
      -s /bin/bash -r -b /home demouser 2>/dev/null
    mkdir -p /home/demouser
    chown demouser:users /home/demouser
}

_unicore_setup() {
    /usr/sbin/groupadd -r unicore 2>/dev/null    
    /usr/sbin/useradd -c "UNICORE" -g unicore \
      -s /bin/false -r -d /tmp unicore 2>/dev/null
    mkdir -p /opt/unicore

    /usr/sbin/groupadd -r demouser 2>/dev/null    
    /usr/sbin/useradd -c "Demo user" -g unicore \
      -s /bin/bash -r demouser 2>/dev/null

    mkdir -p /opt/unicore
    chown unicore:unicore /opt/unicore
    cd /opt/unicore
    
    echo "Downloading TSI..."
    sudo -u unicore git clone https://github.com/UNICORE-EU/tsi.git
    cd tsi
    sudo -u unicore ./Install.sh slurm /opt/unicore/tsi_slurm
    sed -i "s/__VERSION__/8.3.0/" /opt/unicore/tsi_slurm/lib/TSI.py
    cat > /opt/unicore/tsi_slurm/conf/tsi.properties <<EOF

# (autogenerated)


tsi.njs_machine=localhost

tsi.njs_port=27654

tsi.my_addr=0.0.0.0

tsi.my_port=14433

tsi.enforce_gids_consistency=true

tsi.fail_on_invalid_gids=false

tsi.default_job_name=UnicoreJob

tsi.setfacl=setfacl
tsi.getfacl=getfacl
tsi.acl./=NONE

tsi.usersCacheTtl=600

tsi.safe_dir=/tmp

EOF

    /opt/unicore/tsi_slurm/bin/start.sh

}

_main() {
    echo "Setting up Slurm..."
    _munge_setup
    _slurm_setup
    echo "Setting up UNICORE..."
    _unicore_setup
    echo "Creating user(s)..."
    _users_setup

    if [[ "${1:0:1}" = "-" ]]; then
        echo "Please pass a program name to the container!"
        exit 1
    else
        exec "$@"
    fi
}

_main "$@"

