name: UNICORE Docker Image CI

on:
  push:
    paths: 
     - 'unicore-docker-image/**'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd unicore-docker-image; make build
